#!/usr/bin/lua


action = {
  ["A+"] = function (x) print("\r\n"); os.execute("amixer set PCM 2%+1") end,
  ["A0"] = function (x) print("\r\n"); os.execute("amixer set PCM 0%") end,
  ["A-"] = function (x) print("\r\n"); os.execute("amixer set PCM 2%-1") end,
  ["C0"] = function (x) print("\r\n"); os.execute("killall mplayer"); print("Radio off") end, 
  ["C1"] = function (x) print("\r\n"); os.execute("killall mplayer"); os.execute("sleep 3"); os.execute("screen -d -m mplayer mmst://58.211.0.53/1048"); print("苏州电台交通广播") end,
  ["C2"] = function (x) print("\r\n"); os.execute("killall mplayer"); os.execute("sleep 3"); os.execute("screen -d -m mplayer mmst://58.211.0.53/911"); print("苏州电台新闻广播") end,
  ["C3"] = function (x) print("\r\n"); os.execute("killall mplayer"); os.execute("sleep 3"); os.execute("screen -d -m mplayer mmst://58.211.0.53/fm"); print("苏州电台生活广播") end,
  ["C4"] = function (x) print("\r\n"); os.execute("killall mplayer"); os.execute("sleep 3"); os.execute("screen -d -m mplayer mms://audio1.hebradio.com/live1"); print("河北新闻广播") end,
  ["C5"] = function (x) print("\r\n"); os.execute("killall mplayer"); os.execute("sleep 3"); os.execute("screen -d -m mplayer mms://audio1.hebradio.com/live2"); print("河北经济广播") end,
  ["C6"] = function (x) print("\r\n"); os.execute("killall mplayer"); os.execute("sleep 3"); os.execute("screen -d -m mplayer mms://audio1.hebradio.com/live3"); print("河北交通广播") end,
  ["C7"] = function (x) print("\r\n"); os.execute("killall mplayer"); os.execute("sleep 3"); os.execute("screen -d -m mplayer mms://audio1.hebradio.com/live4"); print("河北文艺广播") end,
  ["C8"] = function (x) print("\r\n"); os.execute("killall mplayer"); os.execute("sleep 3"); os.execute("screen -d -m mplayer mms://audio1.hebradio.com/live5"); print("河北生活广播") end,
  ["C9"] = function (x) print("\r\n"); os.execute("killall mplayer"); os.execute("sleep 3"); os.execute("screen -d -m mplayer mms://audio1.hebradio.com/live6"); print("河北音乐广播") end,  
  ["D1"] = function (x) print("\r\n"); os.execute("killall mplayer"); os.execute("sleep 3"); os.execute("screen -d -m mplayer mms://audio1.hebradio.com/live7"); print("河北农村广播") end,
  ["D2"] = function (x) print("\r\n"); os.execute("killall mplayer"); os.execute("sleep 3"); os.execute("screen -d -m mplayer mms://audio1.hebradio.com/live8"); print("河北旅游文化广播") end,
  ["D3"] = function (x) print("\r\n"); os.execute("killall mplayer"); os.execute("sleep 3"); os.execute("screen -d -m mplayer mmst://mediasrv1.iptv.xmg.com.cn/yinyue");print("厦门电台音乐广播") end,
  ["D4"] = function (x) print("\r\n"); os.execute("killall mplayer"); os.execute("sleep 3"); os.execute("screen -d -m mplayer mms://media.vos.com.cn/666"); print("厦门电台1") end,
  ["D5"] = function (x) print("\r\n"); os.execute("killall mplayer"); os.execute("sleep 3"); os.execute("screen -d -m mplayer mms://media.vos.com.cn/783"); print("厦门电台2") end,
  ["D6"] = function (x) print("\r\n"); os.execute("killall mplayer"); os.execute("sleep 3"); os.execute("screen -d -m mplayer mms://media.vos.com.cn/979"); print("厦门电台3") end,
  ["D7"] = function (x) print("\r\n"); os.execute("killall mplayer"); os.execute("sleep 3"); os.execute("screen -d -m mplayer mms://media2.xmg.com.cn/jingji"); print("厦门电台4") end,
  ["D8"] = function (x) print("\r\n"); os.execute("killall mplayer"); os.execute("sleep 3"); os.execute("screen -d -m mplayer mms://media2.xmg.com.cn/xinwen"); print("厦门电台5") end,
  ["D9"] = function (x) print("\r\n"); os.execute("killall mplayer"); os.execute("sleep 3"); os.execute("screen -d -m mplayer mms://media2.xmg.com.cn/yinyue"); print("厦门电台6") end,
  ["E1"] = function (x) print("\r\n"); os.execute("killall mplayer"); os.execute("sleep 3"); os.execute("screen -d -m mplayer mms://media2.xmg.com.cn/tour"); print("厦门电台7") end, 
  ["E2"] = function (x) print("\r\n"); os.execute("killall mplayer"); os.execute("sleep 3"); os.execute("screen -d -m mplayer mms://media2.xmg.com.cn/minnan"); print("厦门电台8") end,
  ["E3"] = function (x) print("\r\n"); os.execute("killall mplayer"); os.execute("sleep 3"); os.execute("screen -d -m mplayer mms://video.fjtv.net/jt?ZHVob25n"); print("海峡之声") end,
}

action[string.sub(os.getenv("QUERY_STRING"),1,2)](string.sub(os.getenv("QUERY_STRING"),3,5))